# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Bejo_UpdateMap
                                 A QGIS plugin
 Update peta seismic dengan database CSV
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-26
        copyright            : (C) 2024 by Aryo Danang
        email                : aryodanang04@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Bejo_UpdateMap class from file Bejo_UpdateMap.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Bejo_UpdateMap import Bejo_UpdateMap
    return Bejo_UpdateMap(iface)
